export const createEmployee = () => ({
    employeeId: null,
    employeeCode: "",
    fullName: "",
    gender: "",
    dateOfBirth: null,
    address: "",
    phoneNumber: "",
    email: "",
    joinDate: null,
    departmentId: null,
    shiftId: null,
    nationalId: "",
    degreeId: null,
    contractId: null,
    positionId: null,
    accountId: null,
    avatarUrl: "profile.jpg",
    createdAt: null,
    createdBy: "",
    updatedBy: "",
    updatedAt: null,
});
